version: '3.8'

services:
  pears-federated:
    env_file:
      - ${PEARS_DIR}/.env
    image: pearsproject/pears-federated:latest
    environment:
      - PEARS_LIST_FILE="/var/lib/pears/network/known_instances.txt"
    ports:
      - "8000:8000"
    volumes:
      - ${PEARS_DIR}/data:/var/lib/pears/data
      - pears-network-data:/var/lib/pears/network

  pears-network:
    env_file:
      - ${PEARS_DIR}/.env
    image: pearsproject/pears-network:latest
    environment:
      - BIND_ADDR=0.0.0.0:7947
      - RPC_ADDR=0.0.0.0:7374
      - PEARS_URL=https://${DOMAIN}
      - LIGHTHOUSE_URL=${LIGHTHOUSE_URL:-}
      - PEARS_LIST_FILE="/var/lib/pears/network/known_instances.txt"
    ports:
      - "6789:6789"
    volumes:
      - pears-network-data:/var/lib/pears/network
    depends_on:
      - pears-federated

  https-portal:
    env_file:
      - .env
    image: steveltn/https-portal:1
    environment:
      DOMAINS: ${DOMAIN} -> http://pears-federated:8000
      STAGE: production
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pears-federated
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:  # Persistent storage for HTTPS certificates and other HTTPS-Portal data
  pears-network-data:  # Persistent storage for network-specific data