"""Added content and license information to URL model

Revision ID: 44660b29fb3d
Revises: 
Create Date: 2026-04-09 21:00:36.881313

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '44660b29fb3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_column('word_vector')
        batch_op.drop_column('DS_vector')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_license', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('allows_reproduction', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('licensing_notes', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=10000), nullable=True))
        batch_op.add_column(sa.Column('url_license', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('allows_reproduction', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('licensing_notes', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_column('licensing_notes')
        batch_op.drop_column('allows_reproduction')
        batch_op.drop_column('url_license')
        batch_op.drop_column('content')

    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_column('licensing_notes')
        batch_op.drop_column('allows_reproduction')
        batch_op.drop_column('url_license')

    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DS_vector', sa.VARCHAR(length=7000), nullable=True))
        batch_op.add_column(sa.Column('word_vector', sa.VARCHAR(length=7000), nullable=True))

    # ### end Alembic commands ###
